id: ca021de97ecf48b5b138dbf35b07bfb0
name: Modification of Boot Configuration
path: /Advanced Threat Detection/Windows Process Monitoring
description: Identifies use of the bcdedit command to delete boot configuration data.
  This tactic is sometimes used as by malware or an attacker as a destructive technique.
type: standard
author: community
entity_type: workbooks
blocks:
- type: text
  code: "|Author|References|\n                 |------|--------|\n               \
    \  |E.M. Anhaus (orignally from Atomic Blue Detections, Endgame), oscd.community|https://github.com/redcanaryco/atomic-red-team/blob/master/atomics/T1490/T1490.yaml<br>https://eqllib.readthedocs.io/en/latest/analytics/c4732632-9c1d-4980-9fa8-1d98c93f918e.html|"
- type: sql
  query: SELECT * FROM SYSMON-PROCESS WHERE (($Image LIKE "%\\bcdedit.exe" AND $CommandLine
    LIKE "%set%") AND (($CommandLine LIKE "%bootstatuspolicy%" AND $CommandLine LIKE
    "%ignoreallfailures%") OR ($CommandLine LIKE "%recoveryenabled%" AND $CommandLine
    LIKE "%no%")))
- type: signal
  DetectionName: Modification of Boot Configuration
  DetectionTactic: Impact
  DetectionTechnique: Inhibit System Recovery
  DetectionScore: 5
  DetectionConfidence: Low
  TargetHost: $System
config: {}
