id: 755319ccf1664b66bc002be9c222f6ac
name: Azure Diagnostic Settings Deletion
path: /Cloud Security/Azure
description: ''
type: standard
author: DNIF
blocks:
- type: sql
  query: Select $OperationName, $User, $Status FROM AZURE WHERE $OperationName='MICROSOFT.INSIGHTS/DIAGNOSTICSETTINGS/DELETE' AND $Status='Succeeded' GROUP BY $OperationName, $User, $Status
- type: signal
  DetectionName: Azure Diagnostic Settings Deletion
  DetectionTactic: Defense Evasion
  DetectionTechnique: Impair Defenses
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  TargetObject: $OperationName
  SuspectUser: $User

