id: f36535b10d3b4c35af4838d770272063
name: User Added as Owner for Azure Application
path: /Cloud Security/Azure
description: ''
type: standard
author: DNIF
blocks:
- type: sql
  query: Select $OperationName, $User, $Status FROM AZURE WHERE $OperationName='Add owner to application' AND $Status='Succeeded' GROUP BY $OperationName, $User, $Status
- type: signal
  DetectionName: User Added as Owner for Azure Application
  DetectionTactic: Persistence
  DetectionTechnique: Account Manipulation
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  TargetObject: $OperationName
  SuspectUser: $User

