id: 901cf81606bf424ca5ff1a25cbf60e5c
name: AWS Config Disabling Channel/Recorder
path: /Cloud Security/Amazon Web Services
description: Detects AWS Config Service disabling
type: standard
author: community
blocks:
- type: text
  code: "Author: vitaliy0x1 \n References: None"
- type: sql
  query:
  - SELECT * FROM CLOUDTRAIL WHERE ($EventSource = "config.amazonaws.com" AND $EventName
    IN ("DeleteDeliveryChannel", "StopConfigurationRecorder"))
- type: signal
  DetectionName: AWS Config Disabling Channel/Recorder
  DetectionTactic: Defense Evasion
  DetectionTechnique: Impair Defenses
