id: 8257ce5941604dff9283b41289c02de3
name: Configuration changed by User
path: /test
description: ''
type: standard
author: Dnif User
blocks:
- query: _fetch * from event where $Stream=ADMINISTRATION AND $Action=CONFIG CHANGED
    AND $Status=PASSED AND $Duration=1h group count_unique $User, $DevSrcIP limit
    100
  type: dql
- query: _checkif int_compare $count_unique >= 3 include
  type: dql
created_by: dnif.user@example.com
timestamp: null
create_tstamp: 1600257689.0308926
last_modified_by: adarsh.shetty@dnif.it
last_modified_tstamp: 1602738137.4999325
scope_id: default
user_id: dnif.user@example.com
cost: null
runtime: null
cron: null
cron_obj: {}
fields: []
properties: []
reference: ''
source: custom
tags: []
