id: 8257ce5941604dff9283b41289c02de3
name: Configuration changed by User
path: /test
description: ''
type: standard
author: Dnif User
blocks:
- type: dql
  query: _fetch * from event where $Stream=ADMINISTRATION AND $Action=CONFIG CHANGED
    AND $Status=PASSED AND $Duration=1h group count_unique $User, $DevSrcIP limit
    100
- type: dql
  query: _checkif int_compare $count_unique >= 3 include
