id: 1ee75a3006ad4ee3b2875fc7887990e3
name: Config File Download
path: /test
description: ''
type: standard
author: Dnif User
blocks:
- query: _fetch * from event where $Action=CONFIGURATION DOWNLOAD AND $Stream=ADMINISTRATION
    AND $Duration=2h group count_unique $DevSrcIP, $User limit 100
  type: dql
