id: 9df6e600b58942f4a9dd72bca6fe3742
name: Azure Application Credential Modification
path: /Cloud Security/Azure
description: ''
type: standard
author: DNIF
blocks:
- type: sql
  query: Select $OperationName, $User, $Status FROM AZURE WHERE $OperationName='Update application - Certificates and secrets management' AND $Status='Succeeded' GROUP BY $OperationName, $User, $Status
- type: signal
  DetectionName: Azure Application Credential Modification
  DetectionTactic: Defense Evasion
  DetectionTechnique: Use Alternate Authentication Material
  DetectionScore: '5'
  DetectionSeverity: Medium
  DetectionConfidence: Low
  SuspectUser: $User

