id: b03c55ab04f143809dc52246629eaa6e
name: Rare port used by applications on network traffic
path: /test
description: ''
type: standard
author: Dnif User
blocks:
- code: _fetch * from event where $Stream=NETWORK-THREAT AND $Duration=10m AND $DstPort=53
    group count_unique $SrcIP, $DstPort limit 100
  query: _fetch * from event where $Stream=NETWORK-THREAT AND $Duration=10m AND $DstPort=53
    group count_unique $SrcIP, $DstPort limit 100
  type: dql
- code: _checkif lookup default <uncommon_ports> join $ScopeID = $ScopeID str_compare
    $DstPort eq $DstPort include
  query: _checkif lookup default <uncommon_ports> join $ScopeID = $ScopeID str_compare
    $DstPort eq $DstPort include
  type: dql
created_by: dnif.user@example.com
timestamp: null
create_tstamp: 1601033334.7305708
last_modified_by: dnif.user@example.com
last_modified_tstamp: 1601033334.7305713
scope_id: default
user_id: dnif.user@example.com
cost: null
runtime: null
cron: null
cron_obj: {}
fields: []
properties: []
reference: ''
source: ''
tags: []
