title: Logging Configuration Changes on Linux Host
author: Mikhail Larin, oscd.community
detection:
- SELECT * FROM AUDITD WHERE ($Type = "PATH" AND $Name IN ("/etc/syslog.conf", "/etc/rsyslog.conf",
  "/etc/syslog-ng/syslog-ng.conf"))
