id: 2db4b59577124c7c98ffb6080ee4ac05
name: Application Protocol Scan detection
path: /test
description: ''
type: scheduled
author: Dnif User
blocks:
- type: dql
  query: _fetch * from event where $Duration=30m AND $Stream=NETWORK-FIREWALL group
    count_unique $SrcIP, $DstIP, $Proto limit 10
- type: dql
  query: _agg count_unique $SrcIP, $DstIP
- type: dql
  query: _checkif int_compare $count_unique > 5 include
- type: dql
  query: _agg count_unique $SrcIP
