id: 2db4b59577124c7c98ffb6080ee4ac05
name: Application Protocol Scan detection
path: /test
description: ''
type: scheduled
author: Dnif User
blocks:
- query: _fetch * from event where $Duration=30m AND $Stream=NETWORK-FIREWALL group
    count_unique $SrcIP, $DstIP, $Proto limit 2
  type: dql
- query: _agg count_unique $SrcIP, $DstIP
  type: dql
- query: _checkif int_compare count_unique > 5 include
  type: dql
- query: _agg count_unique $SrcIP
  type: dql
created_by: dnif.user@example.com
timestamp: 1602770435.890537
create_tstamp: 1600256985.5167336
last_modified_by: adarsh.shetty@dnif.it
last_modified_tstamp: 1602738104.729498
scope_id: default
user_id: dnif.user@example.com
cost: 67.05522537231445
runtime: 35.802471914328635
cron: '*/30 * * * *'
cron_obj: {}
fields: []
properties: []
reference: ''
source: custom
tags: []
