name: Archive Creation
on:
  pull_request:
    branches:
      - master
jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repositoryssss
        uses: actions/checkout@master
        with:
          fetch-depth: 0
      - run: |
          git diff origin/$GITHUB_BASE_REF...origin/$GITHUB_HEAD_REF --name-only | grep -E 'dashboards|reports|workbooks' > diff.txt
          cat diff.txt
